### ISSUE TITLE
Modify to use the visitor pattern

### ISSUE THREAD

**Issue by Mause** [galaxy-team/jupiter#7]

**Comment by milesrout** [comment]
I'm not sure I'm such a fan of the visitor pattern myself.

**Comment by Mause** [comment]
Reasoning?

**Comment by milesrout** [comment]
Almost always there is a cleaner solution. I think "why use it?" is a better question. If you can come up with a good reason to use the visitor pattern and can show it fits the problem then go ahead, I have no against it inherently.

**Comment by Mause** [comment]
Hrm, alright

**Comment by milesrout** [comment]
I don't want to shut you down or anything. We should definitely have a discussion about the architecture of the assembler though, and if we decide on the visitor pattern then, then we decide on the visitor pattern then.

**Comment by Mause** [comment]
Indeed, hence #5

**Comment by milesrout** [comment]
Closed as duplicate of #5
